Update action.yml

diff --git a/.github/actions/dependencies/action.yml b/.github/actions/dependencies/action.yml
--- a/.github/actions/dependencies/action.yml
+++ b/.github/actions/dependencies/action.yml
@@ -17,25 +17,25 @@ runs:
         conan export external/rocksdb rocksdb/6.29.5@
         conan export external/soci soci/4.0.3@
         conan export external/nudb nudb/2.0.8@
-    - name: add Ripple Conan remote
-      shell: bash
-      run: |
-        conan remote list
-        conan remote remove ripple || true
-        # Do not quote the URL. An empty string will be accepted (with
-        # a non-fatal warning), but a missing argument will not.
-        conan remote add ripple ${{ env.CONAN_URL }} --insert 0
-    - name: try to authenticate to Ripple Conan remote
-      id: remote
-      shell: bash
-      run: |
-        # `conan user` implicitly uses the environment variables
-        # CONAN_LOGIN_USERNAME_<REMOTE> and CONAN_PASSWORD_<REMOTE>.
-        # https://docs.conan.io/1/reference/commands/misc/user.html#using-environment-variables
-        # https://docs.conan.io/1/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
-        # https://docs.conan.io/1/reference/env_vars.html#conan-password-conan-password-remote-name
-        echo outcome=$(conan user --remote ripple --password >&2 \
-          && echo success || echo failure) | tee ${GITHUB_OUTPUT}
+#    - name: add Ripple Conan remote
+#      shell: bash
+#      run: |
+#        conan remote list
+#        conan remote remove ripple || true
+#        # Do not quote the URL. An empty string will be accepted (with
+#        # a non-fatal warning), but a missing argument will not.
+#        conan remote add ripple ${{ env.CONAN_URL }} --insert 0
+#    - name: try to authenticate to Ripple Conan remote
+#      id: remote
+#      shell: bash
+#      run: |
+#        # `conan user` implicitly uses the environment variables
+#        # CONAN_LOGIN_USERNAME_<REMOTE> and CONAN_PASSWORD_<REMOTE>.
+#        # https://docs.conan.io/1/reference/commands/misc/user.html#using-environment-variables
+#        # https://docs.conan.io/1/reference/env_vars.html#conan-login-username-conan-login-username-remote-name
+#        # https://docs.conan.io/1/reference/env_vars.html#conan-password-conan-password-remote-name
+#        echo outcome=$(conan user --remote ripple --password >&2 \
+#          && echo success || echo failure) | tee ${GITHUB_OUTPUT}
     - name: list missing binaries
       id: binaries
       shell: bash
